// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenFramework.Api.Data;

#nullable disable

namespace OpenFramework.Api.Migrations
{
    [DbContext(typeof(OpenFrameworkDbContext))]
    [Migration("20260214172639_AddCountryAndBirthDate")]
    partial class AddCountryAndBirthDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpenFramework.Api.Models.Character", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CountryWhereFrom")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("OpenFramework.Api.Models.CharacterPosition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.Property<int>("Z")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CharacterPositions");
                });

            modelBuilder.Entity("OpenFramework.Api.Models.Cloth", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdentCloth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cloths");
                });

            modelBuilder.Entity("OpenFramework.Api.Models.Inventory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("OpenFramework.Api.Models.InventoryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InventoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemGameId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("XSlot")
                        .HasColumnType("int");

                    b.Property<int>("YSlot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("OpenFramework.Api.Models.MorphRelatedWithCharacter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("BrowDown")
                        .HasColumnType("real");

                    b.Property<float>("BrowInnerUp")
                        .HasColumnType("real");

                    b.Property<float>("BrowOuterUp")
                        .HasColumnType("real");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CheekPuff")
                        .HasColumnType("real");

                    b.Property<float>("CheekSquint")
                        .HasColumnType("real");

                    b.Property<float>("EyesLookDown")
                        .HasColumnType("real");

                    b.Property<float>("EyesLookIn")
                        .HasColumnType("real");

                    b.Property<float>("EyesLookOut")
                        .HasColumnType("real");

                    b.Property<float>("EyesLookUp")
                        .HasColumnType("real");

                    b.Property<float>("EyesSquint")
                        .HasColumnType("real");

                    b.Property<float>("EyesWide")
                        .HasColumnType("real");

                    b.Property<float>("JawForward")
                        .HasColumnType("real");

                    b.Property<float>("JawLeft")
                        .HasColumnType("real");

                    b.Property<float>("JawRight")
                        .HasColumnType("real");

                    b.Property<float>("MouthDimple")
                        .HasColumnType("real");

                    b.Property<float>("MouthRollUpper")
                        .HasColumnType("real");

                    b.Property<float>("MouthStretch")
                        .HasColumnType("real");

                    b.Property<float>("NoseSneer")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Morphs");
                });

            modelBuilder.Entity("OpenFramework.Api.Models.Server", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("OpenFramework.Api.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
